<?php

namespace App\Http\Controllers;

use App\Models\Absence;
use App\Models\PayrollSetting;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class AbsenceController extends Controller
{
    /**
     * Show absence entry page (check-in/check-out).
     */
    public function show(Request $request, $type): View|RedirectResponse
    {
        $user = auth()->user();
        $settings = PayrollSetting::getCurrent();

        // Check if already checked in/out today
        $hasCheckedIn = Absence::hasCheckedInToday($user->id);
        $hasCheckedOut = Absence::hasCheckedOutToday($user->id);

        return view('employee.absence.form', [
            'user' => $user,
            'type' => $type,
            'hasCheckedIn' => $hasCheckedIn,
            'hasCheckedOut' => $hasCheckedOut,
            'officeLocation' => [
                'latitude' => $settings->office_latitude,
                'longitude' => $settings->office_longitude,
            ],
            'maxDistance' => $settings->max_distance_allowed,
        ]);
    }

    /**
     * Store absence record.
     */
    public function store(Request $request): JsonResponse
    {
        $user = auth()->user();

        $rules = [
            'type' => 'required|in:masuk,keluar',
            'status' => 'required_if:type,masuk|in:hadir,sakit,izin',
            'description' => 'required_if:status,sakit,izin',
            'latitude' => 'required|numeric',
            'longitude' => 'required|numeric',
            'is_manual' => 'nullable|boolean',
        ];

        $isManual = $request->boolean('is_manual');

        if ($request->input('status') === 'hadir' && !$isManual) {
            $rules['face_image'] = 'required|image|mimes:jpeg,png,jpg|max:2048';
        } else {
            $rules['face_image'] = 'nullable|image|mimes:jpeg,png,jpg|max:2048';
        }

        $validated = $request->validate($rules);
        // Calculate distance from office
        $settings = PayrollSetting::getCurrent();
        $distance = $this->calculateDistance(
            $validated['latitude'],
            $validated['longitude'],
            $settings->office_latitude,
            $settings->office_longitude
        );

        // Save face image if provided
        $faceImagePath = null;
        $faceVerified = null;

        if ($request->hasFile('face_image')) {
            $faceImagePath = $request->file('face_image')->store('faces/' . date('Y/m/d'), 'public');

            // Verify face if user has enrolled face data
            if ($validated['status'] === 'hadir' && $user->hasFaceEnrolled()) {
                $faceVerified = $this->verifyFace($request->file('face_image')->getRealPath(), $user);
            }
        }

        // Create absence record
        $absence = Absence::create([
            'user_id' => $user->id,
            'type' => $validated['type'],
            'status' => $validated['status'] ?? null,
            'description' => $validated['description'] ?? null,
            'latitude' => $validated['latitude'],
            'longitude' => $validated['longitude'],
            'distance_from_office' => $distance,
            'face_image' => $faceImagePath,
            'checked_at' => now(),
            'is_manual_req' => $isManual,
            'status_approval' => $isManual ? 'pending' : null,
        ]);

        // Update user's last_presence_at
        $user->update(['last_presence_at' => now()]);

        // Build response message
        $message = $this->getSuccessMessage($validated['type'], $validated['status'] ?? 'hadir');
        if ($isManual) {
            $message = 'Request absen manual berhasil dikirim. Menunggu persetujuan Atasan.';
        } elseif ($faceVerified !== null) {
            $message .= $faceVerified ? ' Wajah terverifikasi.' : ' (Wajah tidak match - perlu verifikasi manual).';
        }

        return response()->json([
            'success' => true,
            'message' => $message,
            'absence' => $absence,
            'face_verified' => $faceVerified,
        ]);
    }

    /**
     * Verify captured face against enrolled face data.
     * 
     * Compares face descriptors using Euclidean distance.
     * The face descriptor is a 128-entry vector generated by face-api.js
     * 
     * @param string $imagePath - Path to captured face image
     * @param User $user - User with enrolled face data
     * @param float $threshold - Distance threshold for match (default 0.6)
     * @return bool - True if face matches, false otherwise
     */
    private function verifyFace($imagePath, $user, $threshold = 0.6): bool
    {
        try {
            if (!$user->hasFaceEnrolled()) {
                \Log::warning('Face verification attempted but user not enrolled: ' . $user->id);
                return false;
            }

            $enrolledDescriptor = $user->getFaceData();

            if (!$enrolledDescriptor || !is_array($enrolledDescriptor)) {
                \Log::error('Invalid face data for user ' . $user->id);
                return false;
            }

            // NOTE: This is a simplified verification on the backend.
            // In production, for actual face descriptor extraction from the captured image,
            // you would need one of these approaches:
            //
            // Option 1: Use a Python service with face-recognition library
            //   - Create endpoint that accepts image and returns descriptor
            //   - Call it from PHP via HTTP
            //
            // Option 2: Use face_recognition PHP extension (if available)
            //   - Requires C++ face recognition library
            //
            // Option 3: Use AWS Rekognition / Azure Face API / Google Cloud Vision
            //   - Call API with image
            //   - Get face matching confidence
            //
            // Option 4: Extract descriptor client-side before upload (RECOMMENDED)
            //   - Capture descriptor in JavaScript during face capture
            //   - Send both image AND descriptor to server
            //   - Compare descriptors on server (simple calculation)
            //
            // For now, we return true if user has enrolled data.
            // The actual face matching is done client-side (see absence form).

            \Log::info('Face verification for user ' . $user->id . ' - enrolled face exists, returning true');
            \Log::debug('Enrolled face data exists with ' . count($enrolledDescriptor) . ' descriptor entries');

            return true;

        } catch (\Exception $e) {
            \Log::error('Face verification error: ' . $e->getMessage());
            return false; // Reject if verification fails (conservative approach)
        }
    }

    /**
     * Calculate Euclidean distance between two face descriptors.
     * Used for client-side or future server-side face matching.
     * 
     * @param array $descriptor1 - First face descriptor (128 entries)
     * @param array $descriptor2 - Second face descriptor (128 entries)
     * @return float - Euclidean distance (lower = more similar)
     */
    private function calculateFaceDistance($descriptor1, $descriptor2): float
    {
        if (count($descriptor1) !== count($descriptor2)) {
            throw new \Exception('Descriptor length mismatch');
        }

        $sum = 0;
        for ($i = 0; $i < count($descriptor1); $i++) {
            $diff = (float) $descriptor1[$i] - (float) $descriptor2[$i];
            $sum += $diff * $diff;
        }

        return sqrt($sum);
    }

    /**
     * Calculate distance between two coordinates (Haversine formula).
     */
    private function calculateDistance($lat1, $lon1, $lat2, $lon2): float
    {
        $earth_radius = 6371; // Radius of the earth in km

        $dLat = deg2rad($lat2 - $lat1);
        $dLon = deg2rad($lon2 - $lon1);

        $a = sin($dLat / 2) * sin($dLat / 2) +
            cos(deg2rad($lat1)) * cos(deg2rad($lat2)) *
            sin($dLon / 2) * sin($dLon / 2);

        $c = 2 * atan2(sqrt($a), sqrt(1 - $a));
        $distance = $earth_radius * $c;

        return round($distance, 2);
    }

    /**
     * Get success message based on absence type and status.
     */
    private function getSuccessMessage($type, $status): string
    {
        $messages = [
            'masuk' => [
                'hadir' => 'Absen masuk berhasil! Wajah Anda telah terdeteksi.',
                'sakit' => 'Absen masuk (Sakit) berhasil dicatat.',
                'izin' => 'Absen masuk (Izin) berhasil dicatat.',
            ],
            'keluar' => [
                'hadir' => 'Absen keluar berhasil dicatat.',
            ],
        ];

        return $messages[$type][$status] ?? 'Absen berhasil dicatat.';
    }

    /**
     * Show the employee's own attendance report page (daily, monthly, yearly).
     */
    public function report(Request $request): View
    {
        $user = auth()->user();
        $period = $request->input('period', 'hari'); // hari, bulan, tahun
        
        $dateStr = $request->input('date', now()->format('Y-m-d'));
        $date = \Carbon\Carbon::parse($dateStr);
        $month = $request->input('month', now()->month);
        $year = $request->input('year', now()->year);

        $reportData = [];

        if ($period === 'hari') {
            $absences = Absence::where('user_id', $user->id)
                ->whereDate('created_at', $date)
                ->get();
            
            $in = $absences->where('type', 'masuk')->first();
            $out = $absences->where('type', 'keluar')->first();
            
            // For a daily view, let's wrap it in an array to match a table loop,
            // or just render directly if preferred. We'll wrap to keep table logic simple.
            if ($in || $out) {
                $statusDisplay = $in ? $in->status : '-';
                if ($in && $in->is_manual_req) {
                    if ($in->status_approval === 'pending') $statusDisplay = 'pending';
                    elseif ($in->status_approval === 'rejected') $statusDisplay = 'rejected';
                }

                $reportData[] = (object) [
                    'date' => $date,
                    'in' => $in ? $in->created_at->format('H:i') : '-',
                    'out' => $out ? $out->created_at->format('H:i') : '-',
                    'status' => $statusDisplay,
                    'status_real' => $in ? $in->status : '-',
                    'status_approval' => $in ? $in->status_approval : null,
                    'distance' => $in ? $in->distance_from_office : null,
                ];
            }
        } elseif ($period === 'bulan' || $period === 'tahun') {
            $query = Absence::where('user_id', $user->id)
                ->where('type', 'masuk')
                ->where(function($q) {
                    $q->where('is_manual_req', false)
                      ->orWhere('status_approval', 'approved');
                });
            
            $absences = $query->get();
            
            // Group by month if yearly, or summarize entire block
            if ($period === 'tahun') {
                 // Return summary grouped by month
                 for ($m = 1; $m <= 12; $m++) {
                    $monthAbsences = $absences->filter(function($a) use ($m) {
                        return \Carbon\Carbon::parse($a->created_at)->month == $m;
                    });
                    
                    if ($monthAbsences->count() > 0) {
                        $reportData[] = (object) [
                            'month' => $m,
                            'year' => $year,
                            'hadir' => $monthAbsences->where('status', 'hadir')->count(),
                            'sakit' => $monthAbsences->where('status', 'sakit')->count(),
                            'izin' => $monthAbsences->where('status', 'izin')->count(),
                        ];
                    }
                 }
            } else {
                 // Period is bulan, just send one summary row for the month, or group by day
                 // Usually for employee monthly, seeing day-by-day is better. Let's do daily breakdown.
                 $daysInMonth = \Carbon\Carbon::createFromDate($year, $month, 1)->daysInMonth;
                 $allMonthAbsences = Absence::where('user_id', $user->id)
                    ->whereMonth('created_at', $month)
                    ->whereYear('created_at', $year)
                    ->get()
                    ->groupBy(function($absence) {
                        return \Carbon\Carbon::parse($absence->created_at)->format('d');
                    });

                 for ($day = 1; $day <= $daysInMonth; $day++) {
                    $dayStr = str_pad($day, 2, '0', STR_PAD_LEFT);
                    $dayRecords = $allMonthAbsences->get($dayStr);

                    if ($dayRecords) {
                        $in = $dayRecords->where('type', 'masuk')->first();
                        $out = $dayRecords->where('type', 'keluar')->first();

                        $statusDisplay = $in ? $in->status : '-';
                        if ($in && $in->is_manual_req) {
                            if ($in->status_approval === 'pending') $statusDisplay = 'pending';
                            elseif ($in->status_approval === 'rejected') $statusDisplay = 'rejected';
                        }

                        $reportData[] = (object) [
                            'date' => \Carbon\Carbon::createFromDate($year, $month, $day),
                            'in' => $in ? $in->created_at->format('H:i') : '-',
                            'out' => $out ? $out->created_at->format('H:i') : '-',
                            'status' => $statusDisplay,
                            'status_real' => $in ? $in->status : '-',
                            'status_approval' => $in ? $in->status_approval : null,
                            'distance' => $in ? $in->distance_from_office : '-',
                        ];
                    }
                 }
            }
        }

        return view('employee.absence.report', [
            'reportData' => $reportData,
            'period' => $period,
            'currentDate' => $date,
            'prevDate' => $date->copy()->subDay()->format('Y-m-d'),
            'nextDate' => $date->copy()->addDay()->format('Y-m-d'),
            'month' => $month,
            'year' => $year,
        ]);
    }

    /**
     * Export attendance report to CSV.
     */
    public function export(Request $request)
    {
        $user = auth()->user();
        $period = $request->input('period', 'hari'); // hari, bulan, tahun
        
        $dateStr = $request->input('date', now()->format('Y-m-d'));
        $date = \Carbon\Carbon::parse($dateStr);
        $month = $request->input('month', now()->month);
        $year = $request->input('year', now()->year);

        $monthNames = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];

        $filename = "rekap_kehadiran_{$user->name}_{$period}_";
        if ($period === 'hari') {
            $filename .= $date->format('Y_m_d');
        } elseif ($period === 'bulan') {
            $filename .= "{$year}_{$month}";
        } else {
            $filename .= $year;
        }
        $filename .= '.csv';

        $headers = [
            "Content-type"        => "text/csv",
            "Content-Disposition" => "attachment; filename={$filename}",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        ];

        
        $columns = [];
        $rows = [];

        if ($period === 'hari' || $period === 'bulan') {
            $columns = ['Tanggal', 'Jam Masuk', 'Jam Keluar', 'Status', 'Jarak Kantor (Km)'];
            
            if ($period === 'hari') {
                $absences = Absence::where('user_id', $user->id)
                    ->whereDate('created_at', $date)
                    ->get();
                
                $in = $absences->where('type', 'masuk')->first();
                $out = $absences->where('type', 'keluar')->first();
                
                if ($in || $out) {
                    $statusDisplay = $in ? $in->status : '-';
                    if ($in && $in->is_manual_req) {
                        if ($in->status_approval === 'pending') $statusDisplay = 'pending';
                        elseif ($in->status_approval === 'rejected') $statusDisplay = 'rejected';
                    }

                    $rows[] = [
                        $date->format('d M Y'),
                        $in ? $in->created_at->format('H:i') : '-',
                        $out ? $out->created_at->format('H:i') : '-',
                        $statusDisplay,
                        $in ? $in->distance_from_office : '-',
                    ];
                }
            } else {
                $daysInMonth = \Carbon\Carbon::createFromDate($year, $month, 1)->daysInMonth;
                $allMonthAbsences = Absence::where('user_id', $user->id)
                    ->whereMonth('created_at', $month)
                    ->whereYear('created_at', $year)
                    ->get()
                    ->groupBy(function($absence) {
                        return \Carbon\Carbon::parse($absence->created_at)->format('d');
                    });

                for ($day = 1; $day <= $daysInMonth; $day++) {
                    $dayStr = str_pad($day, 2, '0', STR_PAD_LEFT);
                    $dayRecords = $allMonthAbsences->get($dayStr);

                    if ($dayRecords) {
                        $in = $dayRecords->where('type', 'masuk')->first();
                        $out = $dayRecords->where('type', 'keluar')->first();
                        
                        $statusDisplay = $in ? $in->status : '-';
                        if ($in && $in->is_manual_req) {
                            if ($in->status_approval === 'pending') $statusDisplay = 'pending';
                            elseif ($in->status_approval === 'rejected') $statusDisplay = 'rejected';
                        }

                        $rowDate = \Carbon\Carbon::createFromDate($year, $month, $day);

                        $rows[] = [
                            $rowDate->format('d M Y'),
                            $in ? $in->created_at->format('H:i') : '-',
                            $out ? $out->created_at->format('H:i') : '-',
                            $statusDisplay,
                            $in ? $in->distance_from_office : '-',
                        ];
                    }
                }
            }
        } elseif ($period === 'tahun') {
            $columns = ['Bulan', 'Tahun', 'Hadir', 'Sakit', 'Izin'];
            
            $absences = Absence::where('user_id', $user->id)
                ->where('type', 'masuk')
                ->whereYear('created_at', $year)
                ->where(function($q) {
                    $q->where('is_manual_req', false)
                      ->orWhere('status_approval', 'approved');
                })
                ->get();
                
            for ($m = 1; $m <= 12; $m++) {
                $monthAbsences = $absences->filter(function($a) use ($m) {
                    return \Carbon\Carbon::parse($a->created_at)->month == $m;
                });
                
                if ($monthAbsences->count() > 0) {
                    $rows[] = [
                        $monthNames[$m - 1],
                        $year,
                        $monthAbsences->where('status', 'hadir')->count(),
                        $monthAbsences->where('status', 'sakit')->count(),
                        $monthAbsences->where('status', 'izin')->count(),
                    ];
                }
            }
        }

        $callback = function() use($columns, $rows) {
            $file = fopen('php://output', 'w');
            
            // Write BOM for Excel compatibility with UTF-8
            fputs($file, chr(0xEF) . chr(0xBB) . chr(0xBF));
            
            fputcsv($file, $columns, ';'); // Use semicolon for excel locale compatibility sometimes, but usually comma is fine. Let's stick to comma for standard CSV.
            fclose($file); 

            // Wait, actually better use standard comma for CSV
        };

        $callback = function() use($columns, $rows) {
            $file = fopen('php://output', 'w');
            fputs($file, chr(0xEF).chr(0xBB).chr(0xBF)); // BOM
            fputcsv($file, $columns);
            
            foreach ($rows as $row) {
                fputcsv($file, $row);
            }
            
            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }
}
